# Generated by Django 3.2.4 on 2021-06-26 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('date_of_event', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_display', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('main_image', models.ImageField(upload_to='events/%Y/%m/%d/')),
                ('image_1', models.ImageField(blank=True, upload_to='events/%Y/%m/%d/')),
                ('image_2', models.ImageField(blank=True, upload_to='events/%Y/%m/%d/')),
                ('image_3', models.ImageField(blank=True, upload_to='events/%Y/%m/%d/')),
                ('image_4', models.ImageField(blank=True, upload_to='events/%Y/%m/%d/')),
                ('image_5', models.ImageField(blank=True, upload_to='events/%Y/%m/%d/')),
                ('image_6', models.ImageField(blank=True, upload_to='events/%Y/%m/%d/')),
                ('image_7', models.ImageField(blank=True, upload_to='events/%Y/%m/%d/')),
                ('image_8', models.ImageField(blank=True, upload_to='events/%Y/%m/%d/')),
                ('image_9', models.ImageField(blank=True, upload_to='events/%Y/%m/%d/')),
                ('image_10', models.ImageField(blank=True, upload_to='events/%Y/%m/%d/')),
                ('registered_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
