# Generated by Django 3.2.4 on 2021-11-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211126_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='events/%Y/%m/%d/'),
        ),
    ]
