# Generated by Django 3.2.4 on 2021-11-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_auto_20211126_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
