# Generated by Django 3.2.4 on 2021-11-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
