# Generated by Django 3.2.4 on 2021-06-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limelight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limelight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='limelight/thumbnail'),
        ),
    ]
