# Generated by Django 3.2.4 on 2021-06-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limelight', '0004_alter_limelight_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limelight',
            name='year_published',
            field=models.DateField(),
        ),
    ]
